# Generated by Django 2.1.7 on 2019-04-05 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussion_board', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='article',
            new_name='discussion',
        ),
    ]
